### ISSUE TITLE
Broken due to update

### ISSUE THREAD

**Issue by VoidedWinter** [Alesseon/ONI-BottlesToPipes#7]
Crashes on startup due to the big asteroid update.  A similar mod is throwing identical error messages on crash, and a solution was posted as follows:

"Klei moved NO_FILTER_TINT from FilteredStorage to TreeFilterable. I swapped FilteredStoreage.NO_FILTER_TINT to TreeFilterable.NO_FILTER_TINT and recompiled the .dll and it seems like it resolved the issue."

Actual error message is as follows:

MissingFieldException: Field 'FilteredStorage.NO_FILTER_TINT' not found.

UnityEngine.GameObject:AddComponent()
EntityTemplateExtensions:AddOrGet(GameObject)
Alesseon.Building.Config.LiquidBottleEmptierConfig:ConfigureBuildingTemplate(GameObject, Tag)
BuildingConfigManager:RegisterBuilding(IBuildingConfig)
GeneratedBuildings:LoadGeneratedBuildings_Patch21(List`1)
LegacyModMain:LoadBuildings(List`1)
LegacyModMain:Load()
Assets:CreatePrefabs()
Assets:OnPrefabInit()
KMonoBehaviour:InitializeComponent()
KMonoBehaviour:Awake()
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)
Util:KInstantiate(GameObject, Vector3, Quaternion, GameObject, String, Boolean, Int32)
Util:KInstantiate(GameObject, GameObject, String)
LaunchInitializer:Update()

**Comment by odr4g0no** [comment]
[DebugConsole][1]: MissingFieldException: Field 'FilteredStorage.NO_FILTER_TINT' not found.
UnityEngine.GameObject:AddComponent()
EntityTemplateExtensions:AddOrGet(GameObject) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/Mods/EntityTemplates.cs:1304)
Alesseon.Building.Config.LiquidBottleEmptierConfig:ConfigureBuildingTemplate(GameObject, Tag)
BuildingConfigManager:RegisterBuilding_Patch0(Object, IBuildingConfig)
GeneratedBuildings:LoadGeneratedBuildings_Patch130(List`1)
LegacyModMain:LoadBuildings_Patch1(List`1)
LegacyModMain:Load() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/Mods/LegacyModMain.cs:26)
Assets:CreatePrefabs() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Assets.cs:229)
Assets:OnPrefabInit() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Assets.cs:223)
KMonoBehaviour:InitializeComponent() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/KMonoBehaviour.cs:132)
KMonoBehaviour:Awake() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/KMonoBehaviour.cs:44)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)
Util:KInstantiate(GameObject, Vector3, Quaternion, GameObject, String, Boolean, Int32) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/Util.cs:226)
Util:KInstantiate(GameObject, GameObject, String) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/Util.cs:198)
LaunchInitializer:Update() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/LaunchInitializer.cs:58)

**Comment by Alesseon** [comment]
Thanks for reporting it there.
@VoidedWinter Thank you, it did work.
I wonder why they cannot maintan some stable codebase or at least "hey, this is going to be deleted"
