### ISSUE TITLE
project isn't compatible with latest game release version (update to Harmony2.0)

### ISSUE THREAD

**Issue by hilgner82** [Alesseon/ONI-BottlesToPipes#9]
Take a look at the latest update news from "the big merge update"
Modding Update instructions https://forums.kleientertainment.com/forums/topic/130712-oni-is-upgrading-to-harmony-20/

**Comment by Alesseon** [comment]
Thanks for letting me know. 
It was really just the configuration changes and they upgraded their .Net version.

**Comment by hilgner82** [comment]
Thx a lot 👍
